services:

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    depends_on:
      - db
    ports:
      - "8000:5000" 
  #frontend:
    #build:
      #context: ./front-end
      #dockerfile: Dockerfile
    #container_name: frontend_app
    #restart: always
    #depends_on:
      #- backend
    #ports:
      #- "3000:3000"

 
  #chatbot:
    #build:
      #context: ./chatbot
      #dockerfile: Dockerfile
    #container_name: chatbot_service
    #restart: always
    #depends_on:
      #- db
    #environment:
      #MODEL: llama3
      #RAG_ENABLED: "true"
    #ports:
      #- "5000:5000"
  scraper:
    build:
      context: ./web_scraper
      dockerfile: Dockerfile
    container_name: webscraper
    volumes:
      - ./web_scraper:/app

    command: python scraper.py
    depends_on:
      - db
volumes:
  postgres_data:
